From openjdk:17-slim as build

MAINTAINER namehalnijhawan3641@gmail.com

COPY target/accounts-service-0.0.1-SNAPSHOT.jar accounts-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT [ "java" , "-jar", "/accounts-service-0.0.1-SNAPSHOT.jar"]